# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e572329d7071b89302720ae892e48b221d3e079b1ebee930eec21cfe5e9e01b51d25c1538910399b70f0da4e3c59ebfc78ef648ec00c76c29ee5aae2358d040b

test:
  secret_key_base: c3a65f0e36f2caa97552facd088cfcece9b576439694aabac8734ae309aa08f7f1178ad824e7d9fd8ad6330f232a9d63f366a43f1a59cad9b9bce287804738b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
